In [24]:
import tensorflow as tf
tf.__version__

'2.19.0'

In [2]:
#creating a simple tensors using tf.constant()
scalar=tf.constant(7)
scalar

I0000 00:00:1755522995.642149    5508 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1725 MB memory:  -> device: 0, name: NVIDIA GeForce MX350, pci bus id: 0000:01:00.0, compute capability: 6.1


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
vector = tf.constant([5,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7], dtype=int32)>

In [4]:
matrix = tf.constant([[10,7],[2,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  4]], dtype=int32)>

In [5]:
tensor = tf.constant([[[2,3],[3,4]],
                      [[2,3],[5,6]], 
                      [[4,6],[8,9]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [3, 4]],

       [[2, 3],
        [5, 6]],

       [[4, 6],
        [8, 9]]], dtype=int32)>

In [6]:
#creating a tensor with tf.variable
#let see the diff between constant and tf.variable 
variable = tf.Variable([10,7])

constant  = tf.constant([10,7])
print(variable,constant)
#here we can able to change the values after assingning inside the variable but in constant it is fixed
print(variable[0].assign(8))

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)> tf.Tensor([10  7], shape=(2,), dtype=int32)
<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>


In [7]:
#random tensors
random = tf.random.normal(shape=(3,2))
random

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.69141316,  0.8040538 ],
       [-1.7057098 ,  0.1399742 ],
       [ 1.9215403 , -2.4257045 ]], dtype=float32)>

In [8]:
#shuffle
random = tf.random.Generator.from_seed(42)
random = random.normal(shape=(3,2))
print(random)
tf.random.shuffle(random)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [9]:
#zeros and ones
print(tf.zeros([3,2]))
print(tf.ones([3,2]))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [10]:
#convert numpy into tensor
import numpy as np
numpy = np.arange(1,25)
numpy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [11]:
tensor = tf.constant(numpy)
tensor

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [12]:
#indexing tensors

tensor[:2]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 2])>

In [13]:
#manipulating tensors
a = tf.constant([[1,2],[3,4]])
a+3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7]], dtype=int32)>

In [14]:
#matrix multiplication(the inner dim should match the outer dim)
tf.matmul(a,a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [15]:
a = tf.constant([[1,2],
                 [4,5],
                 [5,6]])
b = tf.constant([[1,2],
                 [4,5],
                 [5,6]])
tf.matmul(a,b)

2025-08-18 18:46:36.365563: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2]


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [16]:
b = tf.reshape(b,shape=(2,3))
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [5, 5, 6]], dtype=int32)>

In [17]:
print(a @ b)
print(tf.matmul(a,b))

tf.Tensor(
[[11 12 16]
 [29 33 46]
 [35 40 56]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[11 12 16]
 [29 33 46]
 [35 40 56]], shape=(3, 3), dtype=int32)


In [18]:
tf.tensordot(a,b,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 12, 16],
       [29, 33, 46],
       [35, 40, 56]], dtype=int32)>

In [22]:
"""
Aggregating Tensors

This section of the code focuses on aggregating tensors, which refers to the process of combining multiple tensors into a single tensor. 
Aggregation can involve various operations such as summation, averaging, or finding the maximum value across the specified dimensions of the tensors. 
This is useful in many machine learning and data processing tasks where you need to reduce the dimensionality of data or summarize information.
"""
# Aggregating tensors
#1.Absolute values

a= tf.constant([-3,-5])
a


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -5], dtype=int32)>

In [23]:
tf.abs(a)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [33]:
import pandas as pd
import numpy as np

rand_val = tf.constant(np.random.randint(0,100,size=50))
rand_val

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([30, 85, 85, 35,  6, 27, 34,  3, 98, 97, 98, 24, 76,  4, 62, 42, 90,
       70, 39, 29, 44, 18, 82, 52, 37, 66, 97, 34, 96, 63, 70, 49, 14, 58,
       48, 29, 15, 98, 81, 89,  1, 94, 89, 60, 65, 52, 65, 38, 99, 21])>

In [34]:
#min max mean
tf.reduce_min(rand_val),tf.reduce_max(rand_val),tf.reduce_mean(rand_val),tf.reduce_sum(rand_val)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=55>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2758>)

In [41]:
#positional maximum and minimum
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [45]:
f[tf.argmax(f)],tf.reduce_max(f)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>)

In [48]:
f[tf.argmin(f)],tf.reduce_min(f)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>)

In [54]:
#sqeezing the tensors(removing all single dimensions)
tf.random.set_seed(42)
sq = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
sq

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [56]:
tf.squeeze(sq),tf.squeeze(sq).shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [57]:
#one hot encoding tensors
list = [0,1,2,3]
depth = 4
tf.one_hot(list,depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [58]:
tf.one_hot(list,depth=3,on_value="Abi",off_value="Mah")

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'Abi', b'Mah', b'Mah'],
       [b'Mah', b'Abi', b'Mah'],
       [b'Mah', b'Mah', b'Abi'],
       [b'Mah', b'Mah', b'Mah']], dtype=object)>

In [59]:
#squaring,log,square root
rand = tf.range(1,10)
rand

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [60]:
tf.square(rand)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [63]:
tf.sqrt(tf.cast(rand,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [64]:
tf.math.log(tf.cast(rand,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [65]:
#tensor and numpy
tens = tf.constant(np.array([1,2,3,4,5]))
tens

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

In [66]:
#convert tensore back to numpy
np.array(tens)

array([1, 2, 3, 4, 5])